### PR TITLE
removing custom List type.

### PR DESCRIPTION
**Pull request by devnexen**
it made probably sense back in 1998, but it has a couple of uaf issues, it is more worthy to use the standard std::list type rather than trying to fix it.

### CODE REVIEW

**Review by 0lvin — APPROVED** [review]

**Comment by 0lvin** [comment]
Thank you!

**Comment by 0lvin** [comment]
Could you please check? Code is crashed on quit.

```
Thread 1 "quake2" received signal SIGSEGV, Segmentation fault.
0x0000ffffc94dac1c in CScript::Free (this=0xaaaaac69b140, DoData=true) at src/game/ds.cpp:2058
2058			delete (*iev);
(gdb) p iev
$1 = <error reading variable: Cannot access memory at address 0xaaa006701c6d>
(gdb) bt
#0  0x0000ffffc94dac1c in CScript::Free (this=0xaaaaac69b140, DoData=true) at src/game/ds.cpp:2058
#1  0x0000ffffc94da6a4 in CScript::~CScript (this=0xaaaaac69b140, __in_chrg=<optimized out>) at src/game/ds.cpp:1973
#2  0x0000ffffc94d593c in ShutdownScripts (Complete=1) at src/game/ds.cpp:284
#3  0x0000ffffc9417608 in ShutdownGame () at src/game/g_main.c:349
#4  0x0000aaaaaab7a9dc in SV_ShutdownGameProgs () at src/server/sv_game.c:374
#5  0x0000aaaaaab7e57c in SV_Shutdown (finalmsg=0xaaaaaab8b7b0 "Server quit\n", reconnect=false) at src/server/sv_main.c:684
#6  0x0000aaaaaab3a330 in Com_Quit () at src/common/clientserver.c:307
#7  0x0000aaaaaaae40f0 in CL_Quit_f () at src/client/cl_main.c:330
#8  0x0000aaaaaab4232c in Cmd_ExecuteString (text=0xffffffffe9a0 "quit") at src/common/cmdparser.c:1063
#9  0x0000aaaaaab40b90 in Cbuf_Execute () at src/common/cmdparser.c:242
#10 0x0000aaaaaaae55c0 in CL_Frame (packetdelta=29974, renderdelta=29974, timedelta=29974, packetframe=true,
    renderframe=true) at src/client/cl_main.c:814
#11 0x0000aaaaaab4c564 in Qcommon_Frame (usec=29974) at src/common/frame.c:699
#12 0x0000aaaaaab4b710 in Qcommon_Mainloop () at src/common/frame.c:215
#13 0x0000aaaaaab4be50 in Qcommon_Init (argc=1, argv=0xfffffffff108) at src/common/frame.c:431
#14 0x0000aaaaaab83c98 in main (argc=1, argv=0xfffffffff108) at src/backends/unix/main.c:145
```

**Comment by devnexen** [comment]
Aaaah little forgotten thing ...
Can you try the following line 2058 ?

```patch
- Events.erase(iev);
+ iev = Events.erase(iev);
```

**Comment by 0lvin** [comment]
Looks good, thank you. I will apply in next commit

**Pull request merged**
